import React from "react";
import "./SourcePanel.css";
import { ReactComponent as Cross } from "../../assets/Cross.svg";

interface RetrievedChunks {
  original_name: string;
  doc_id: string;
  page_num: number;
  chunk_text: string;
  size?: number;
  document_group_name: string;
}

interface SourcePanelProps {
  retrieved_chunks: RetrievedChunks;
  onLookClick: () => void;
  onCloseClick: () => void; 
  onDownloadClick: () => void;
}

const SourcePanel: React.FC<SourcePanelProps> = ({
  retrieved_chunks,
  onLookClick,
  onCloseClick,
  onDownloadClick,
}) => {
  return (
    <div className="source-section custom-scrollbar">
      <div className="source-section-header">
        <h3>{retrieved_chunks.original_name}</h3>
        <div className="cross-container">
          <button className="close-button" onClick={onCloseClick}>
            <Cross />
          </button>
        </div>
      </div>

      <div className="source-section-body">
        {/* <div className="preview-img">
          <img src={Preview} alt="PDF Preview" className="bordered-img" />
        </div> */}
        <div className="button-container">
          <button className="look-button" onClick={onLookClick}>
            보기
          </button>
          <button className="download-button" onClick={onDownloadClick}> 다운로드 </button>
        </div>

        <div className="line" />

        <div className="source-section-text">
          <h3>파일 세부정보</h3>

          {/* <div>
            <div className="small-text-container">
              <h4>문서 요약</h4>
              <p className="small-text">Generated by PhnyX LLM</p>
            </div>
            <p>{retrieved_chunks.document_summary}</p>
          </div> */}

          <div>
            <h4>참고 내용</h4>
            <p>{retrieved_chunks.chunk_text}</p>
          </div>

          <div>
            <h4>문서 그룹</h4>
            <p>{retrieved_chunks.document_group_name}</p>
          </div>

          {/* <div>
            <h4>문서 그룹</h4>
            <p>{retrieved_chunks.doc_type}</p>
          </div>

          <div>
            <h4>문서 그룹</h4>
            <p>{retrieved_chunks.score} / 1</p>
          </div>

          <div>
            <h4>문서 그룹</h4>
            <p>{retrieved_chunks.file_size}</p>
          </div>

          <div>
            <h4>문서 그룹</h4>
            <p>{retrieved_chunks.timestamp}</p>
          </div> */}
        </div>
      </div>
    </div>
  );
};

export default SourcePanel;
